### PR TITLE
Weather app

### PR DESCRIPTION
**Pull request by MarkoNS1990**
This is a simple weather app in which you can enter city name and weather info for that city will be shown.
I used fetch API to fetch the data from weather-api.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @MarkoNS1990! This is a good start. You handled the asynchronous code appropriately. However, there are several project requirements you seem to have left out. These include:
- [x] Add a toggle control to determine if the result will be shown in Celsius or Fahrenheit. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
- [x] Your app should change its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
- [x] Use Webpack to manage your project's resources ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/webpack_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
- [x] Once you've configured webpack, all webpack related packages should be included in `package.json` like `webpack`, `webpack-cli`, `webpack-dev-server` etc. Also, those packages should be added as **devDependencies** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
- [x] You are also expected to add scripts that are necessary to build your project in package.json. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

**Review by umararshadbut — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @MarkoNS1990 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes as the previous code reviewer suggested👇.
- [x] Add a toggle control to determine if the result will be shown in Celsius or Fahrenheit. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/weather-app))
- [x] Once you've configured webpack, all webpack related packages should be included in `package.json` like `webpack`, `webpack-cli`, `webpack-dev-server` etc. Also, those packages should be added as devDependencies ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
- [x] You are also expected to add scripts that are necessary to build your project in package.json. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS :  CHANGES REQUIRED  ♻️

@MarkoNS1990 Weldone for implementing the changes 
### Highlight
- [ ] Add a toggle control to determine if the result will be shown in Celsius or Fahrenheit.
### To Improve
- [ ] Your Readme failed to mentioned how to set up `npm`. kindly add it.
- [ ] Kindly use this in your` package.json`
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Marko Zecevic

## To Highlight :tada:

1. The project solves the problem it was supposed to solve.
2. Your PR has a good title and description.
3. You have descriptive git commit messages.


Good job on implementing the changes requested. However, there are some changes that you need to make in order to get your project approved

- [ ] ```npm run start``` script is not working

- [ ] Kindly add in your readme's setup section how to run the project
<hr>


Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇 
### Hello @MarkoNS1990 
Amazing work you have done with the weather app.
You have corrected all previous required reviews. It's a thumbs up for me. 👍🏽 

### [OPTIONAL] Stretch Requirement

- [ ] I just noticed on your README file that you did not explicitly write out the `git clone` command to clone your repo.

You can quickly add this and then go ahead to merge this PR.

Good luck on your next project and Happy Coding 💻 

Code Reviewer
**_Witah Georjane_**

**Pull request merged**
